# Generated by Django 2.2.13 on 2020-09-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gendere',
            new_name='gender',
        ),
    ]
